// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf1aFs-Ik84ZeXgUShIpF8DOd4rU4Z1GU',
    appId: '1:1022426520236:android:c0f16c7cba099df853dd09',
    messagingSenderId: '1022426520236',
    projectId: 'flutter-test-d70d4',
    databaseURL: 'https://flutter-test-d70d4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-test-d70d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuPuYjF95tIOgkOfK_f0iCmnoQoDRtAaU',
    appId: '1:1022426520236:ios:54c42b22ba8f7e2f53dd09',
    messagingSenderId: '1022426520236',
    projectId: 'flutter-test-d70d4',
    databaseURL: 'https://flutter-test-d70d4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-test-d70d4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}